apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portr.fullname" . }}-secret
  labels:
    {{- include "portr.labels" . | nindent 4 }}
type: Opaque
stringData:
  # GitHub OAuth credentials
  PORTR_ADMIN_GITHUB_CLIENT_ID: {{ .Values.config.github.clientId | quote }}
  PORTR_ADMIN_GITHUB_CLIENT_SECRET: {{ .Values.config.github.clientSecret | quote }}

  # Admin encryption key
  PORTR_ADMIN_ENCRYPTION_KEY: {{ .Values.config.encryptionKey | quote }}

  # PostgreSQL configuration
  {{- if .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  PORTR_DB_URL: {{ include "portr.postgresql.connectionString" . | quote }}
  {{- end }}
